### ISSUE TITLE
When using a country with an other currency then $

### ISSUE THREAD

**Issue by murmelbahn** [custom-cards/nintendo-wishlist-card#2]
Hi,

at first I have to thank you for extend the support of the component for other regions.
I've tried the new card / componente with the german eshop and when I display the card
in lovelace you geht a wrong currency. See the image:

[https://s18.directupload.net/images/190724/asa56c93.png](url)

**Comment by boralyl** [comment]
What currency are you expecting to see?  As far as I know Germany uses the Euro, the data you are seeing there is coming directly from Nintendo.  Please correct me if I am wrong.

https://www.nintendo.de/Suche-/Suche-299117.html?q=valiant&f=147394-86-6956

**Comment by murmelbahn** [comment]
Oh the image is not working, I dont know why. Here is another one:

https://ibb.co/w7HTTfJ

As you can see, before the price is the $ and after the price the € symbol.

**Comment by boralyl** [comment]
Ah!  I missed the `$` in the first image.  Thanks for reporting.

**Comment by boralyl** [comment]
This is fixed in the latest release.  You will need to update the custom component and the custom card.
