### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by hudsonbrendon** [custom-cards/nintendo-wishlist-card#4]
any prediction of adding support for hacs? https://hacs.xyz/

**Comment by boralyl** [comment]
I didn't realize this wasn't in hacs.  It used to be back in the early days, but this hasn't been updated since hacs has improved. I'll make some updates to get it supported.

**Comment by boralyl** [comment]
Looks like it was already in the default repo: https://github.com/hacs/default/blob/master/plugin#L46  I was just missing the `hacs.json` which I've added.  I think it should show up by default now.
