### ISSUE TITLE
card not listed after installation

### ISSUE THREAD

**Issue by lauris-nl** [custom-cards/nintendo-wishlist-card#6]
I could not get this custom card to work with the latest hass and hacs. The custom card does not show up in the card list. Even after a reboot.

Ps it is possible to install the cart manual  (if you fix the double - and indentation)

**Comment by boralyl** [comment]
@lauris-nl This custom card isn't setup to be configured via the UI at the moment.  You will need to use raw yaml to add the card to your dashboard.

**Comment by lauris-nl** [comment]
Exactly! Can that be fixed?

29 sep. 2023 21:16:24 Aaron Godfrey ***@***.***>:

**Comment by boralyl** [comment]
It looks like it can be: https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card/#graphical-card-configuration

I just got a new computer and haven't gotten the HA devcontainer setup yet to test it out.  When I finally get around to that I'll give it a try and ping you on this issue.

**Comment by boralyl** [comment]
@lauris-nl I experimented a little and got it mostly working.  I don't have enough time to fully polish it but you can add the card from the UI now.  See https://github.com/custom-cards/nintendo-wishlist-card/releases/tag/v2.2.1

You'll still need to ensure you add the resource to the js file via the instructions in the readme or through the UI using dashboard resources: https://developers.home-assistant.io/docs/frontend/custom-ui/registering-resources/

**Comment by lauris-nl** [comment]
Wow, many thanks.
That are some great improvements.

Greetings.

30 sep. 2023 00:26:08 Aaron Godfrey ***@***.***>:
