### ISSUE TITLE
suggestion asked

### ISSUE THREAD

**Issue by Link0Darck** [custom-cards/nintendo-wishlist-card#7]
Is there a way to add the games we want to know about without using code?
Thanks in advance

```
nintendo_wishlist:
  scan_interval:
    # at least one of the following must be specified:
    days: 0
    hours: 0
    minutes: 1
    seconds: 0
    milliseconds: 0
  country: FR
  wishlist:
    - "DOOM Eternal: The Ancient Gods, Épisode 1"
    - Terraria
    - "The Legend of Zelda: Tears of the Kingdom"
    - "Kirby's Return to Dream Land Deluxe"
    - "World War Z"
    - "Pokémon Violet"
```

**Comment by boralyl** [comment]
@Link0Darck At the moment this component can only be configured via yaml and not via the UI.  I don't currently have any plans to update that in the near future.  I'm hoping one day I can just read the wish list directly from the nintendo website instead of having to maintain a separate list in HA.
